---
- hosts: kube-master
  become: true
  gather_facts: true
  
  roles:
    - role: common
    - role: master

- hosts: kube-worker
  become: true
  gather_facts: true
  
  roles:
    - role: common
    - role: worker
